version: "3.8"

services:
  # Service pour le frontend Vue.js
  frontend:
    image: node:16
    container_name: vuejs-front
    volumes:
      - ./frontend:/app
    working_dir: /app
    ports:
      - "8080:8080"
    command: sh -c "npm install && npm run serve"
    depends_on:
      - backend

  # Service pour le backend Symfony + PHP
  backend:
    image: php:8.1-fpm
    container_name: symfony-back
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "mysql://user:password@db:3306/challenge_formation"

  # Service pour phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8081:80"
    depends_on:
      - db

  # Service pour MySQL
  db:
    image: mysql:8.0
    container_name: mysql-db
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: challenge_formation
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

volumes:
  db_data:
